macro(add_cxx_compile_options OPTIONS)
	add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:${OPTIONS}>")
endmacro()

if (MSVC)
	add_cxx_compile_options("/W4")
	add_cxx_compile_options("/WX")
else()
	add_cxx_compile_options("-Wall")
	add_cxx_compile_options("-Wextra")
	add_cxx_compile_options("-pedantic")
	add_cxx_compile_options("-Wshadow")
	add_cxx_compile_options("-Wno-unused-parameter")
endif()
